### ISSUE TITLE
Artheon infrastructure requirements and TF grid migration workflow

### ISSUE THREAD

**Issue by scottyeager** [freeflownation/www_artheon#5]
Placing this here for now, although may not be the optimal repo, to document requirements and plans for migrating Artheon the ThreeFold Grid.

Artheon is currently using:
* 9 virtual servers. Two have 1TB HDD, the rest have 64GB
* Database is Postgres, currently hosted on VPS with larger storage
* Three VPS are used for Kubernetes cluster (this should be an easy move to VDC)
* One VPS used for Gitlab runner
* Gamer servers are packaged as Docker containers
* There is an Python based API, the main backend source of the data. And the Golang based backend service used for text chat and Vivox (voice chat) authentication.
* AWS S3 storage to store art objects. And it is planned also to store community/user created mods. (Can replace with our Minio solution?)

Future goals/needs:
* Want users to be able to upload custom maps and locations to explore with others, first of all the photogrammetry scanned locations.
* One more hard thing from the DevOps perspective is to allow users to schedule their worlds to run at our public servers.

Plan:
* Deploy a VDC and test launching existing Kubernetes workloads within it (requires a very small amount of TFT)
* Test integrating what's on VDC with the other components running on existing infrastructure
* Deploy a Minio solution, potentially utilizing the VDCs QSFS provisions, copy objects from AWS S3 and test
* Evaluating remaining components and how to migrate them

**Comment by despiegk** [comment]
why do we need this now?
its ok it works, wherever it comes from
I rather wait for TFGrid 3.0

**Comment by scottyeager** [comment]
I am just documenting requirements and suggesting a plan to move forward. If there is consensus that it's best to wait for 3.0, that is of course fine. Should anything here be made obsolete by the 3.0 release, let's make a note so that any efforts are efficient.

That said, Artheon is a partner that's ready to migrate to the Grid and the VDC needs as much testing as possible. Announcing Grid utilization by a partner would be exactly the kind of news our community wants to hear right now. Focusing some energy on this seems like an easy win for the whole ecosystem to me.
